from typing import Protocol

from .types import TokenUsage, ToolState


class ChannelRenderer(Protocol):
    async def send_text(self, text: str) -> None: ...
    async def update_status(self, text: str) -> None: ...
    async def show_error(self, error: str) -> None: ...
    async def show_completion(self, tools: list[ToolState], usage: TokenUsage) -> None: ...
